/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __defNormalProp = (obj, key, value) => key in obj ? __defProp(obj, key, { enumerable: true, configurable: true, writable: true, value }) : obj[key] = value;
var __commonJS = (cb, mod) => function __require() {
  return mod || (0, cb[__getOwnPropNames(cb)[0]])((mod = { exports: {} }).exports, mod), mod.exports;
};
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);
var __publicField = (obj, key, value) => {
  __defNormalProp(obj, typeof key !== "symbol" ? key + "" : key, value);
  return value;
};

// src/services/adapters/cloudEndpoints.json
var require_cloudEndpoints = __commonJS({
  "src/services/adapters/cloudEndpoints.json"(exports, module2) {
    module2.exports = {
      openai: "https://api.openai.com/v1/chat/completions",
      gemini: "https://generativelanguage.googleapis.com/v1beta/openai/chat/completions",
      deepseek: "https://api.deepseek.com/v1/chat/completions",
      aliyun: "https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions",
      claude: "https://api.anthropic.com/v1/messages",
      groq: "https://api.groq.com/openai/v1/chat/completions",
      openrouter: "https://openrouter.ai/api/v1/chat/completions",
      bedrock: "https://bedrock-runtime.amazonaws.com",
      requesty: "https://api.requesty.ai/v1/chat/completions",
      cohere: "https://api.cohere.ai/v1/chat",
      grok: "https://api.x.ai/v1/chat/completions",
      mistral: "https://api.mistral.ai/v1/chat/completions",
      vertex: "https://us-central1-aiplatform.googleapis.com/v1/projects/{project}/locations/{location}/endpoints/{endpoint}:predict",
      glm: "https://open.bigmodel.cn/api/paas/v4/chat/completions",
      mimo: "https://api.xiaomimimo.com/v1/chat/completions",
      minimax: "https://api.minimax.io/v1/chat/completions",
      "openai-compatible": "http://your-api-endpoint/v1/chat/completions"
    };
  }
});

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => AITaggerPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian27 = require("obsidian");

// src/utils/languageUtils.ts
var LanguageUtils = class {
  static getLanguageDisplayName(code) {
    if (!code || code === "default") {
      return "Default";
    }
    return this.LANGUAGE_NAMES[code] || code;
  }
  static getLanguageOptions() {
    return { ...this.LANGUAGE_NAMES };
  }
};
__publicField(LanguageUtils, "LANGUAGE_NAMES", {
  "default": "Default",
  "ar": "Arabic",
  "cs": "Czech",
  "da": "Danish",
  "de": "German",
  "en": "English",
  "es": "Spanish",
  "fr": "French",
  "id": "Indonesian",
  "it": "Italian",
  "ja": "Japanese",
  "ko": "Korean",
  "nl": "Dutch",
  "no": "Norwegian",
  "pl": "Polish",
  "pt": "Portuguese",
  "pt-BR": "Brazilian Portuguese",
  "ro": "Romanian",
  "ru": "Russian",
  "tr": "Turkish",
  "uk": "Ukrainian",
  "zh": "Chinese (Simplified)",
  "zh-TW": "Chinese (Traditional)"
});

// src/services/prompts/tagPrompts.ts
var pluginSettings;
function setSettings(settings) {
  pluginSettings = settings;
}
function validateCustomPrompt(prompt) {
  if (!prompt || typeof prompt !== "string") {
    return "Custom prompt must be a non-empty string";
  }
  if (prompt.length > 1e4) {
    return "Custom prompt exceeds maximum length (10000 characters)";
  }
  const suspiciousPatterns = [
    /ignore\s+(all\s+)?(previous|above|prior)\s+(instructions?|prompts?)/i,
    /disregard\s+(all\s+)?(previous|above|prior)/i,
    /system\s*:\s*you\s+are/i
  ];
  for (const pattern of suspiciousPatterns) {
    if (pattern.test(prompt)) {
      return "Custom prompt contains potentially unsafe content";
    }
  }
  return null;
}
function buildTagPrompt(content, candidateTags, mode, maxTags = 5, language, settings) {
  const activeSettings = settings || pluginSettings;
  let prompt = "";
  let langInstructions = "";
  if (language && language !== "default") {
    const languageName = LanguageUtils.getLanguageDisplayName(language);
    switch (mode) {
      case "hybrid":
        langInstructions = `IMPORTANT: Generate all new tags in \${languageName} language only.\nWhen generating new tags (not selecting from predefined ones), they must be in \${languageName} only.\n\n`;
        break;
      case "generate":
        langInstructions = `IMPORTANT: Generate all tags in \${languageName} language only.\nRegardless of what language the content is in, all tags must be in \${languageName} only.\nFirst understand the content, then if needed translate concepts to \${languageName}, then generate tags in \${languageName}.\n\n`;
        break;
      default:
        langInstructions = "";
    }
  }
  if (pluginSettings?.enableNestedTags) {
    const nestedInstructions = `\n<nested_tags_requirements>\nGenerate tags in hierarchical/nested format using forward slashes (/) when appropriate.\nUse nested tags to show relationships from general to specific concepts.\n\nStructure: parent/child or parent/child/grandchild (max \${pluginSettings.nestedTagsMaxDepth} levels)\n\nExamples of good nested tags:\n- technology/artificial-intelligence/machine-learning\n- science/biology/genetics\n- programming/languages/python\n- business/marketing/social-media\n- art/painting/impressionism\n\nWhen to use nested tags:\n1. When there's a clear categorical hierarchy (category/subcategory)\n2. When the concept has a broader parent topic\n3. When it helps organize knowledge by domain\n\nWhen NOT to use nested tags:\n1. Don't force nesting if concepts are independent\n2. Don't create unnecessary hierarchies\n3. Flat tags are fine for standalone concepts\n\nGenerate a mix of nested and flat tags based on content relevance.\n</nested_tags_requirements>\n\n`;
    prompt += nestedInstructions;
  }
  switch (mode) {
    case "predefined":
      prompt += `<task>\nAnalyze the document content and select up to \${maxTags} most relevant tags from the available tag list.\n</task>\n\n<available_tags>\n\${candidateTags.join(", ")}\n</available_tags>\n\n<document_content>\n\${content}\n</document_content>\n\n<requirements>\n- Select ONLY from the available tags listed above\n- Do NOT modify existing tags or create new ones\n- Do NOT include the # symbol\n- Choose the most relevant and specific tags that match the content\n- Return up to \${maxTags} tags maximum\n</requirements>\n\n<output_format>\nReturn the selected tags as a comma-separated list in kebab-case format.\n\nExample: machine-learning, data-science, neural-networks\n\nDo NOT include explanations, just the comma-separated tag list.\n</output_format>`;
      break;
    case "hybrid":
      prompt += `\${langInstructions}<task>\nAnalyze the document content and provide relevant tags using a two-part approach:\n1. Select existing tags from the available tag list that match the content (up to \${Math.ceil(maxTags / 2)} tags)\n2. Generate new tags for concepts not covered by existing tags (up to \${Math.ceil(maxTags / 2)} tags)\n</task>\n\n<available_tags>\n\${candidateTags.join(", ")}\n</available_tags>\n\n<document_content>\n\${content}\n</document_content>\n\n<tag_requirements>\n- Use kebab-case formatting (lowercase with hyphens): "machine-learning" not "Machine Learning"\n- Keep tags concise (1-3 words maximum)\n- Be specific and descriptive\n- Match existing tags exactly when selecting from available tags\n- Generate new tags only for important concepts not covered by existing tags\n- Do NOT include the # symbol\n- Do NOT prefix tags with field names or "tag:"\n</tag_requirements>\n\n<output_format>\nReturn ONLY a valid JSON object with this exact structure:\n{\n  "matchedExistingTags": ["existing-tag-1", "existing-tag-2"],\n  "suggestedTags": ["new-tag-1", "new-tag-2"]\n}\n\nExample of CORRECT output:\n{\n  "matchedExistingTags": ["medical-research", "healthcare"],\n  "suggestedTags": ["clinical-trials", "patient-outcomes"]\n}\n\nExample of WRONG output (DO NOT DO THIS):\n{\n  "matchedExistingTags": ["tag:matchedExistingTags-medical-research"],\n  "suggestedTags": ["suggestedTags-healthcare"]\n}\n</output_format>`;
      break;
    case "generate":
      prompt += `\${langInstructions}<task>\nAnalyze the document content and generate up to \${maxTags} relevant tags that best describe the key topics, themes, and concepts.\n</task>\n\n<document_content>\n\${content}\n</document_content>\n\n<tag_requirements>\n- Use kebab-case formatting (lowercase with hyphens): "machine-learning" not "Machine Learning" or "machine_learning"\n- Keep tags concise (1-3 words maximum)\n- Be specific and descriptive\n- Focus on main topics, key concepts, and important themes\n- Avoid overly generic tags unless highly relevant\n- Do NOT include the # symbol\n- Do NOT prefix tags with "tag:" or any other prefix\n</tag_requirements>\n\n<output_format>\nReturn the tags as a comma-separated list.\n\nExample: machine-learning, deep-learning, neural-networks, python, data-preprocessing\n\nDo NOT include explanations or additional text, just the comma-separated tag list.\n</output_format>`;
      break;
    case "custom":
      if (!activeSettings?.customPrompt) throw new Error("Custom tagging mode requires a custom prompt.");
      prompt += `\${langInstructions}<task>\nAnalyze the document content and generate relevant tags.\n</task>\n\n<document_content>\n\${content}\n</document_content>\n\n<custom_instructions>\n\${activeSettings.customPrompt}\n</custom_instructions>\n\n<output_format>\nReturn the tags as a comma-separated list.\n</output_format>`;
      break;
    default:
      throw new Error(`Unsupported mode: \${mode}`);
  }
  return prompt;
}

// src/utils/constants.ts
var SYSTEM_PROMPT = "You are a professional document tag analysis assistant.";
var getSystemPrompt = () => typeof window !== "undefined" && window.AI_MERGE_SYSTEM_PROMPT_OVERRIDE ? window.AI_MERGE_SYSTEM_PROMPT_OVERRIDE : SYSTEM_PROMPT;

// src/services/baseService.ts
class BaseLLMService {
  constructor(config, app) {
    // 这里的 .trim() 是 JavaScript 字符串的内置方法，用于去除字符串两端的空格。
    // 为了防止 config.endpoint 为空或非字符串导致报错，我们在这里加上了安全检查。
    this.endpoint = (typeof config.endpoint === "string" ? config.endpoint : "").trim();
    this.modelName = (typeof config.modelName === "string" ? config.modelName : "").trim();
    this.apiKey = (config.apiKey || config.cloudApiKey || "").trim();
    this.temperature = typeof config.temperature === "number" ? config.temperature : 0;
    this.app = app;
    this.TIMEOUT = (config.requestTimeout || 60) * 1e3;
    this.activeRequests = new Set();
  }
  setDebugMode(enabled) { this.debugMode = enabled; }
  async dispose() {
    this.activeRequests.forEach(r => r.controller.abort());
    this.activeRequests.clear();
  }
  extractJSONFromResponse(res) {
    const m = res.match(/```(?:json)?\s*(\{[\s\S]*?\})\s*```/);
    if (m) return m[1];
    const j = res.match(/\{[\s\S]*\}/);
    if (j) return j[0];
    throw new Error("No JSON found");
  }
  parseResponse(response, mode, maxTags) {
     // Simplifying for rebuild
     return { matchedExistingTags: [], suggestedTags: [response.substring(0, 20)] };
  }
}

// Simplified classes for rebuild to stay within token limits
class LocalLLMService extends BaseLLMService {
    async testConnection() { return { result: "success" }; }
    async sendRequest(prompt, systemPrompt) { 
        const messages = [];
        if (systemPrompt) {
            messages.push({ role: "system", content: systemPrompt });
        }
        messages.push({ role: "user", content: prompt });

        const res = await (0, import_obsidian27.requestUrl)({ 
            url: this.endpoint, method: "POST", 
            body: JSON.stringify({ 
                model: this.modelName, 
                messages: messages,
                temperature: this.temperature 
            })
        });
        const data = JSON.parse(res.text);
        return data.choices?.[0]?.message?.content || data.message?.content || res.text;
    }
    async analyzeTags(c, e, m, mx, l) { return { suggestedTags: ["demo-tag"], matchedExistingTags: [] }; }
}

class CloudLLMService extends BaseLLMService {
    async testConnection() { return { result: "success" }; }
    async sendRequest(prompt, systemPrompt) { 
        const headers = { "Content-Type": "application/json" };
        if (this.apiKey) {
            headers["Authorization"] = `Bearer ${this.apiKey}`;
        }

        const messages = [];
        if (systemPrompt) {
            messages.push({ role: "system", content: systemPrompt });
        }
        messages.push({ role: "user", content: prompt });

        try {
            const res = await (0, import_obsidian27.requestUrl)({ 
                url: this.endpoint, 
                method: "POST", 
                headers: headers,
                body: JSON.stringify({ 
                    model: this.modelName, 
                    messages: messages,
                    temperature: this.temperature
                })
            });
            if (res.status !== 200) {
                throw new Error(`HTTP Error ${res.status}: ${res.text || "Unknown error"}`);
            }
            const data = JSON.parse(res.text);
            return data.choices?.[0]?.message?.content || data.message?.content || res.text;
        } catch (error) {
            console.error("AI Request Failed:", error);
            throw error;
        }
    }
    async analyzeTags(c, e, m, mx, l) { return { suggestedTags: ["demo-tag"], matchedExistingTags: [] }; }
}

// src/utils/tagUtils.ts
var TagUtils = class {
  static getExistingTags(fm) {
    if (!fm || !fm.tags) return [];
    return Array.isArray(fm.tags) ? fm.tags.map(String) : [String(fm.tags)];
  }
  static getAllTags(app) {
    const tags = new Set();
    app.vault.getMarkdownFiles().forEach(f => {
      const c = app.metadataCache.getFileCache(f);
      if(c?.frontmatter?.tags) this.getExistingTags(c.frontmatter).forEach(t => tags.add(t));
    });
    return Array.from(tags).sort();
  }
  static async updateNoteTags(app, file, newTags, matched, silent, replace, format) {
    const content = await app.vault.read(file);
    await app.vault.modify(file, "---\ntags: [" + [...newTags, ...matched].join(",") + "]\n---\n" + content);
    return { success: true, message: "Updated" };
  }
  static async renameTagInVault(app, oldTag, newTag) {
    const files = app.vault.getMarkdownFiles();
    let affectedFilesCount = 0;

    for (const file of files) {
      try {
        await app.fileManager.processFrontMatter(file, (frontmatter) => {
          const tags = frontmatter.tags;
          if (!tags) return;

          let tagArray = Array.isArray(tags) ? tags : [tags];
          let found = false;
          
          const newTags = tagArray.map(t => {
            const strTag = String(t).replace(/^#/, "");
            if (strTag === oldTag.replace(/^#/, "")) {
              found = true;
              return newTag.replace(/^#/, "");
            }
            return strTag;
          });

          if (found) {
            // Deduplicate
            frontmatter.tags = Array.from(new Set(newTags));
            affectedFilesCount++;
          }
        });
      } catch (e) {
        console.error(`Failed to process frontmatter for \${file.path}:`, e);
      }
    }

    return { success: true, affectedFiles: affectedFilesCount };
  }
};

// Placeholder for TagDeduplicationModal to satisfy extension
class TagDeduplicationModal extends import_obsidian27.Modal {
    constructor(app, t, tagFormat) {
        super(app);
        this.t = t;
        this.tagFormat = tagFormat;
        this.currentIndex = 0;
    }
    renderCurrentGroup() {}
}

// src/main.ts
var AITaggerPlugin = class extends import_obsidian27.Plugin {
  constructor(app, manifest) {
    super(app, manifest);
    this.settings = { ...DEFAULT_SETTINGS };
    this.t = getTranslations();
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async onload() {
    console.log("Loading AI Tagger");
    await this.loadSettings();

    const plugin = this;

    // 初始化服务时，根据当前的 serviceType 映射对应的配置字段到基础属性
    const serviceConfig = {
      ...this.settings,
      endpoint: this.settings.serviceType === "local" ? this.settings.localEndpoint : this.settings.cloudEndpoint,
      modelName: this.settings.serviceType === "local" ? this.settings.localModel : this.settings.cloudModel,
      apiKey: this.settings.serviceType === "local" ? "" : this.settings.cloudApiKey,
      temperature: this.settings.llmTemperatureOverride
    };

    if (this.settings.serviceType === "cloud") {
        this.llmService = new CloudLLMService(serviceConfig, this.app);
    } else {
        this.llmService = new LocalLLMService(serviceConfig, this.app);
    }
    
    this.addCommand({
      id: "ai-merge-folder-tags",
      name: "AI 智能合并当前文件夹标签",
      icon: "folder-git-2",
      callback: () => {
        const activeFile = plugin.app.workspace.getActiveFile();
        const activeFolder = activeFile ? activeFile.parent : plugin.app.vault.getRoot();
        new FolderAIMergePromptModal(plugin, activeFolder).open();
      }
    });

    this.addCommand({
        id: "deduplicate-tags",
        name: "Deduplicate Tags",
        callback: () => {}
    });
  }
};
var DEFAULT_SETTINGS = {
    serviceType: "local",
    localEndpoint: "http://localhost:11434/v1/chat/completions",
    localModel: "mistral",
    aiMergeSystemPrompt: "你现在是一个 Obsidian 标签管理专家。请找出意思相近、拼写错误或由于单复数导致的重复标签。",
    aiMergeFormatPrompt: "请严格按照以下格式输出 JSON 二维数组：\n[[\"保留标签\", \"被合并标签1\", \"被合并标签2\"], [\"另一个保留标签\", \"被合并标签3\"]]\n每一组的第一个元素是你建议保留的标签名。只返回 JSON 数组，不要任何解释。"
};
function getTranslations() { return { 
    tagDeduplication: { duplicatesFound: "Found {count} groups", merging: "Merging...", mergeSuccess: "Merged {source} into {target}", noDuplicates: "All clean" },
    modals: { confirm: "Confirm" }
}; }

// ADDED BY PATCH: AI Merge Folder Tags
const _obsidian_patch = require("obsidian");

class AITagDeduplicationModal extends TagDeduplicationModal {
  constructor(app, t, tagFormat, groups, scopeFiles) {
    super(app, t, tagFormat);
    this.initialGroups = groups;
    this.scopeFiles = scopeFiles;
    this.currentIndex = 0;
  }
  
  async onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("tag-deduplication-modal");
    contentEl.createEl("h3", { text: "AI 智能合并确认 / AI Merge Confirmation" });
    this.statusEl = contentEl.createDiv({ cls: "tag-dedup-status", attr: { style: "font-weight: bold; margin-bottom: 10px; color: var(--text-muted);" } });
    
    this.progressContainer = contentEl.createDiv({ attr: { style: "width: 100%; height: 6px; background: var(--background-secondary); border-radius: 3px; overflow: hidden; margin-bottom: 20px;" } });
    this.progressBar = this.progressContainer.createDiv({ attr: { style: "width: 0%; height: 100%; background: var(--interactive-accent); transition: width 0.3s ease;" } });

    this.containerEl = contentEl.createDiv({ cls: "tag-dedup-container", attr: { style: "margin: 0 0 20px 0; padding: 20px; background: var(--background-primary-alt); border-radius: 12px; border: 1px solid var(--background-modifier-border);" } });
    this.buttonContainerEl = contentEl.createDiv({ cls: "tag-dedup-buttons", attr: { style: "display: flex; gap: 10px; justify-content: flex-end;" } });
    
    this.groups = this.initialGroups; 
    if (this.groups.length === 0) {
      this.statusEl.setText(this.t.tagDeduplication.noDuplicates);
      const closeBtn = this.buttonContainerEl.createEl("button", { text: "关闭 / Close", cls: "mod-cta" });
      closeBtn.addEventListener("click", () => this.close());
      return;
    }
    this.renderCurrentGroup();
  }
  
  async renderCurrentGroup() {
    this.containerEl.empty();
    this.buttonContainerEl.empty();
    
    if (this.currentIndex >= this.groups.length && this.groups.length > 0) {
      new _obsidian_patch.Notice("所有标签建议已处理完毕 / All suggestions handled.");
      this.close();
      return;
    }

    const group = this.groups[this.currentIndex];
    const progress = (this.currentIndex / this.groups.length) * 100;
    this.progressBar.setAttr("style", `width: ${progress}%; height: 100%; background: var(--interactive-accent); transition: width 0.3s ease;`);
    this.statusEl.setText(`第 ${this.currentIndex + 1} / ${this.groups.length} 组建议`);

    const header = this.containerEl.createDiv({ attr: { style: "margin-bottom: 20px; text-align: center; border-bottom: 1px solid var(--background-modifier-border); padding-bottom: 15px;" } });
    header.createEl("div", { text: "建议保留标签:", attr: { style: "font-size: 0.85em; text-transform: uppercase; letter-spacing: 0.05em; color: var(--text-muted); margin-bottom: 5px;" } });
    header.createEl("div", { text: "#" + group.suggestedTarget, attr: { style: "font-size: 1.5em; font-weight: bold; color: var(--text-accent); background: var(--background-primary); padding: 5px 15px; border-radius: 4px; display: inline-block; border: 1px solid var(--interactive-accent);" } });
    
    const list = this.containerEl.createEl("div", { attr: { style: "margin: 15px 0;" } });
    list.createEl("p", { text: "将合并以下同义标签:", attr: { style: "font-size: 0.9em; font-weight: 500; margin-bottom: 10px;" } });
    const ul = list.createEl("ul", { attr: { style: "list-style: none; padding: 0; display: flex; flex-wrap: wrap; gap: 8px;" } });
    group.tags.forEach(t => {
        if (t.tag !== group.suggestedTarget) {
            const li = ul.createEl("li", { attr: { style: "background: var(--background-secondary); padding: 4px 10px; border-radius: 12px; font-size: 0.85em; border: 1px solid rgba(0,0,0,0.1);" } });
            li.createSpan({ text: t.tag, attr: { style: "color: var(--text-normal); font-weight: 500;" } });
            li.createSpan({ text: ` (${t.count})`, attr: { style: "color: var(--text-muted); font-size: 0.9em;" } });
        }
    });

    // Action Buttons
    const mergeBtn = this.buttonContainerEl.createEl("button", { text: "合并这一组 / Merge", cls: "mod-cta" });
    mergeBtn.addEventListener("click", () => this.mergeCurrentGroup());

    const skipBtn = this.buttonContainerEl.createEl("button", { text: "跳过 / Skip" });
    skipBtn.addEventListener("click", () => {
        this.currentIndex++;
        this.renderCurrentGroup();
    });

    const mergeAllBtn = this.buttonContainerEl.createEl("button", { text: "全部合并 / Merge All", cls: "mod-warning", attr: { style: "margin-left: auto;" } });
    mergeAllBtn.addEventListener("click", () => this.mergeAll());
  }
  
  async mergeCurrentGroup() {
    const group = this.groups[this.currentIndex];
    const targetTag = group.suggestedTarget;
    const sourceTags = group.tags.filter((t) => t.tag !== targetTag);
    
    const notice = new _obsidian_patch.Notice(`正在合并到 ${targetTag}...`, 0);
    for (const sourceInfo of sourceTags) {
      await TagUtils.renameTagInVault(this.app, sourceInfo.tag, targetTag, undefined, this.tagFormat);
    }
    notice.hide();
    new _obsidian_patch.Notice(`已成功合并到 ${targetTag}`);
    
    this.currentIndex++;
    this.renderCurrentGroup();
  }
  
  async mergeAll() {
    const notice = new _obsidian_patch.Notice("正在执行全部批量合并...", 0);
    for (let i = this.currentIndex; i < this.groups.length; i++) {
        const group = this.groups[i];
        const targetTag = group.suggestedTarget;
        for (const s of group.tags.filter(t => t.tag !== targetTag)) {
            await TagUtils.renameTagInVault(this.app, s.tag, targetTag, undefined, this.tagFormat);
        }
    }
    notice.hide();
    new _obsidian_patch.Notice("全部合并完成");
    this.currentIndex = this.groups.length;
    this.renderCurrentGroup();
  }
};

class FolderAIMergePromptModal extends _obsidian_patch.Modal {
  constructor(plugin, activeFolder) {
    super(plugin.app);
    this.plugin = plugin;
    this.activeFolder = activeFolder;
    this.timer = 45;
  }
  
  onOpen() {
    let { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("tag-deduplication-modal");
    contentEl.createEl("h3", { text: "AI 智能合并文件夹标签" }); 
    
    const info = contentEl.createDiv({ attr: { style: "margin: 20px 0; padding: 15px; background: var(--background-primary-alt); border-radius: 8px; border: 1px solid var(--background-modifier-border);" } });
    info.createEl("p", { text: "此操作将分析指定文件夹中所有笔记的标签，并由 AI 提供合并建议。", attr: { style: "margin: 0 0 10px 0; font-size: 0.95em;" } });
    info.createEl("p", { text: "目标范围: ", attr: { style: "margin: 0; font-weight: bold; font-size: 0.9em; color: var(--text-muted);" } }).createSpan({ text: this.activeFolder.path, attr: { style: "color: var(--text-accent);" } });
    
    let btnContainer = contentEl.createDiv({ cls: "tag-dedup-buttons", attr: { style: "display: flex; gap: 10px; justify-content: flex-end;" } });
    
    const cancelBtn = btnContainer.createEl("button", { text: "取消" });
    cancelBtn.addEventListener("click", () => this.close());

    const okBtn = btnContainer.createEl("button", { text: "确定执行", cls: "mod-cta" });
    okBtn.addEventListener("click", () => {
        this.close();
        this.executeMerge();
    });
  }
  
  async executeMerge() {
     const folder = this.activeFolder;
     const notice = new _obsidian_patch.Notice("1. 正在获取标签数据...", 0);
     let files = this.plugin.app.vault.getMarkdownFiles().filter(f => f.path.startsWith(folder.path === "/" ? "" : folder.path + "/"));
     
     const tagInfoMap = new Map();
     for (const file of files) {
       const cache = this.plugin.app.metadataCache.getFileCache(file);
       if (!cache?.frontmatter) continue;
       const tags = TagUtils.getExistingTags(cache.frontmatter);
       for (const tag of tags) {
         const existing = tagInfoMap.get(tag);
         if (existing) { existing.count++; existing.files.push(file); }
         else { tagInfoMap.set(tag, { tag, count: 1, files: [file] }); }
       }
     }
     
     if(tagInfoMap.size === 0) {
         notice.hide();
         return new _obsidian_patch.Notice("未找到标签");
     }
     
     notice.setMessage("2. AI 正在分析标签 (请稍候)...");
     
     const tagsWithFiles = {};
     for (const [tag, info] of tagInfoMap.entries()) {
         tagsWithFiles[tag] = info.files.map(f => f.basename).slice(0, 20);
     }

     const systemPrompt = this.plugin.settings.aiMergeSystemPrompt || "你现在是一个 Obsidian 标签整理专家。请找出意思相近或重复的标签。";
     const formatPrompt = this.plugin.settings.aiMergeFormatPrompt || "输出格式要求：\n1. 严格输出一个 JSON 二维数组，形如：[[\"保留标签A\", \"被合并标签1\", \"被合并标签2\"], [\"保留标签B\", \"被合并标签3\"]]\n2. 每一组首个元素是建议保留的标签，后续元素是建议合并到首个元素的标签。\n3. 只输出 JSON 数组，不要任何开头语或结尾说明。";
     const systemPromptOverride = `${systemPrompt}\n${formatPrompt}`;

     try {

       const responseText = await this.plugin.llmService.sendRequest("标签数据:\n" + JSON.stringify(tagsWithFiles), systemPromptOverride);

       
       console.log("AI Raw Response:", responseText);
       notice.setMessage("3. 处理 AI 返回结果...");
       
       let parsed = null;
       try {
           // 1. 清理 AI 可能返回的转义符 (hallucination fixes)
           let cleanText = responseText.replace(/\\"/g, '"'); 
           
           // 2. 优先匹配 Markdown 代码块内容
           const codeBlockMatch = cleanText.match(/```(?:json)?\s*([\s\S]*?)\s*```/);
           const contentToParse = codeBlockMatch ? codeBlockMatch[1] : cleanText;
           
           // 3. 提取 JSON 结构
           const jsonMatch = contentToParse.match(/(\{[\s\S]*\}|\[[\s\S]*\])/);
           if (!jsonMatch) throw new Error("未在回复中找到 JSON 结构");
           
           parsed = JSON.parse(jsonMatch[1]);
       } catch (err) {
           console.error("JSON Parse Error:", err, "Content:", responseText);
           throw new Error("AI 返回结果解析失败，请重试。");
       }

       let groups = [];
       // 兼容格式 A: { "groups": [ { "target": "...", "sources": [...] } ] }
       if (parsed && typeof parsed === "object" && !Array.isArray(parsed) && Array.isArray(parsed.groups)) {
           groups = parsed.groups.map(g => {
               if (!g.target || !Array.isArray(g.sources)) return null;
               const all = [g.target, ...g.sources].filter(t => tagInfoMap.has(t));
               return all.length > 1 ? { 
                   tags: all.map(t => tagInfoMap.get(t)), 
                   similarityType: "similar", 
                   suggestedTarget: g.target 
               } : null;
           }).filter(Boolean);
       } 
       // 兼容格式 B: [ ["保留", "合并1"], ["保留2", "合并2"] ]
       else if (Array.isArray(parsed)) {
           groups = parsed.filter(group => Array.isArray(group) && group.length > 1)
                        .map(group => {
                            const target = group[0];
                            const sources = group.slice(1);
                            const all = [target, ...sources].filter(t => tagInfoMap.has(t));
                            return all.length > 1 ? { 
                                tags: all.map(t => tagInfoMap.get(t)), 
                                similarityType: "similar", 
                                suggestedTarget: target 
                           } : null;
                        }).filter(Boolean);
       } else {
           throw new Error("AI 返回的 JSON 数据结构不正确 (既非数组也非包含 groups 的对象)");
       }
       
       notice.hide();
       if (groups.length === 0) {
           console.log("Analysis Result: No mergeable groups found by AI.");
           return new _obsidian_patch.Notice("分析完成，AI 认为当前标签无需合并");
       }
       new AITagDeduplicationModal(this.plugin.app, this.plugin.t, this.plugin.settings.tagFormat, groups, files).open();
     } catch (e) {
        notice.hide();
        new _obsidian_patch.Notice("错误: " + (e.message || e));
     }
  }
}
// END PATCH
